version: 2
project_name: nrdot-collector-releases-nightly
release:
  draft: true
  disable: "true"
builds:
  - id: nrdot-collector-host
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: nrdot-collector-host
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: nrdot-collector-host
    builds:
      - nrdot-collector-host
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" }}{{- else }}{{- .Arch }}{{- end }}{{- with .Arm }}v{{ . }}{{- end }}{{- with .Mips }}_{{ . }}{{- end }}{{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}'
    package_name: nrdot-collector-host
    contents:
      - src: nrdot-collector-host.service
        dst: /lib/systemd/system/nrdot-collector-host.service
      - src: nrdot-collector-host.conf
        dst: /etc/nrdot-collector-host/nrdot-collector-host.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector-host/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    rpm:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    deb:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector-host
    builds:
      - nrdot-collector-host
    formats:
      - deb
      - rpm
    maintainer: New Relic <caos-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector-host
    license: Apache 2.0
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:{{ .Version }}-nightly-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:nightly-amd64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:{{ .Version }}-nightly-arm64'
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:nightly-arm64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector-host:nightly'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:nightly-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector-host:nightly-arm64'
blobs:
  - bucket: nr-releases
    provider: s3
    region: us-east-1
    directory: nrdot-collector-releases/nrdot-collector-host/nightly
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
