project_name: opentelemetry-collector-releases
builds:
  - id: nr-otel-collector
    goos:
      - linux
      # - windows
    goarch:
      - amd64
      # - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: distributions/nr-otel-collector/_build
    binary: nr-otel-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: nr-otel-collector
    builds:
      - nr-otel-collector
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'

    format_overrides:
      - goos: windows
        format: zip

      #         {{- with .Arm }}v{{ . }}{{- end }}
      # {{- with .Mips }}_{{ . }}{{- end }}
      # {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}

nfpms:
  - package_name: nr-otel-collector
    file_name_template: >-
      {{ .PackageName }}_{{ .Version }}_{{ .Os }}_ 
      {{- if (eq (title .Os) "Linux") }}
        {{- .Os }}
      {{ else }}
        {{- .Arch }}
      {{- end }}

    contents:
      - src: distributions/nr-otel-collector/nr-otel-collector.service
        dst: /lib/systemd/system/nr-otel-collector.service
      - src: distributions/nr-otel-collector/nr-otel-collector.conf
        dst: /etc/nr-otel-collector/nr-otel-collector.conf
        type: config|noreplace
      - src: configs/nr-otel-collector.yaml
        dst: /etc/nr-otel-collector/config.yaml
        type: config
    scripts:
      preinstall: distributions/nr-otel-collector/preinstall.sh
      postinstall: distributions/nr-otel-collector/postinstall.sh
      preremove: distributions/nr-otel-collector/preremove.sh
    id: nr-otel-collector
    builds:
      - nr-otel-collector
    formats:
      - deb
    maintainer: New Relic <caos-team@newrelic.com>
    description: OpenTelemetry Collector - nr-otel-collector
    license: Apache 2.0

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: distributions/nr-otel-collector/Dockerfile
    image_templates:
      - cciutea768/nr-otel-collector:{{ .Version }}-rc-amd64
    extra_files:
      - configs/nr-otel-collector.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: distributions/nr-otel-collector/Dockerfile
    image_templates:
      - cciutea768/nr-otel-collector:{{ .Version }}-rc-arm64
    extra_files:
      - configs/nr-otel-collector.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
docker_manifests:
  - name_template: cciutea768/nr-otel-collector:{{ .Version }}-rc
    image_templates:
      - cciutea768/nr-otel-collector:{{ .Version }}-rc-amd64
      - cciutea768/nr-otel-collector:{{ .Version }}-rc-arm64

publishers:
  - name: GH Publisher
    cmd: .github/workflows/scripts/gh_publisher.sh -t {{ .Env.NR_RELEASE_TAG }} -f {{ abs .ArtifactPath }}
    env:
      - GITHUB_TOKEN={{ .Env.GITHUB_TOKEN }}

git:
  # What should be used to sort tags when gathering the current and previous
  # tags if there are more than one tag in the same commit.
  #
  # This is required because of the SemVer tag renaming.
  #
  # Default: `-version:refname`
  tag_sort: -version:creatordate

# Skip creating/updating gh release.
release:
  disable: true

# Skip auto-generating changelog.
changelog:
  skip: true
