.PHONY: ci
ci:
	act -W .github/workflows/ci.yaml

ci_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act -W .github/workflows/ci.yaml \
		--matrix distribution:nrdot-collector-host

ci_nightly_custom_matrix:
	@# repeat --matrix arg for multiple distros
	act schedule -W .github/workflows/ci-nightly.yaml \
		--matrix distribution:nrdot-collector-host