version: 2
project_name: nrdot-collector-releases
release:
  disable: "true"
builds:
  - id: nr-otel-collector
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: nr-otel-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: nr-otel-collector
    builds:
      - nr-otel-collector
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" }}{{- else }}{{- .Arch }}{{- end }}{{- with .Arm }}v{{ . }}{{- end }}{{- with .Mips }}_{{ . }}{{- end }}{{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}'
    package_name: nr-otel-collector
    contents:
      - src: nr-otel-collector.service
        dst: /lib/systemd/system/nr-otel-collector.service
      - src: nr-otel-collector.conf
        dst: /etc/nr-otel-collector/nr-otel-collector.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nr-otel-collector/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    rpm:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    deb:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nr-otel-collector
    builds:
      - nr-otel-collector
    formats:
      - deb
      - rpm
    maintainer: New Relic <caos-team@newrelic.com>
    description: NRDOT Collector - nr-otel-collector
    license: Apache 2.0
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - newrelic/nr-otel-collector:{{ .Version }}-amd64
      - newrelic/nr-otel-collector:latest-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - newrelic/nr-otel-collector:{{ .Version }}-arm64
      - newrelic/nr-otel-collector:latest-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: newrelic/nr-otel-collector:{{ .Version }}
    image_templates:
      - newrelic/nr-otel-collector:{{ .Version }}-amd64
      - newrelic/nr-otel-collector:{{ .Version }}-arm64
  - name_template: newrelic/nr-otel-collector:latest
    image_templates:
      - newrelic/nr-otel-collector:latest-amd64
      - newrelic/nr-otel-collector:latest-arm64
blobs:
  - bucket: nr-releases
    provider: s3
    region: us-east-1
    directory: nrdot-collector-releases/nr-otel-collector/{{ .Version }}
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
