version: 2
project_name: nrdot-collector-releases
release:
  disable: "true"
builds:
  - id: nrdot-collector-k8s
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: nrdot-collector-k8s
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: nrdot-collector-k8s
    builds:
      - nrdot-collector-k8s
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - newrelic/nrdot-collector-k8s:{{ .Version }}-amd64
      - newrelic/nrdot-collector-k8s:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - newrelic/nrdot-collector-k8s:{{ .Version }}-arm64
      - newrelic/nrdot-collector-k8s:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: newrelic/nrdot-collector-k8s:{{ .Version }}
    image_templates:
      - newrelic/nrdot-collector-k8s:{{ .Version }}-amd64
      - newrelic/nrdot-collector-k8s:{{ .Version }}-arm64
  - name_template: newrelic/nrdot-collector-k8s:latest
    image_templates:
      - newrelic/nrdot-collector-k8s:latest-amd64
      - newrelic/nrdot-collector-k8s:latest-arm64
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
